version: "3.6"

services:
    sw-api:
        build: .
        volumes:
            - ./src:/app/src/
        environment:
            ENV: 'dev'
            DB_MONGODB_NAME_TEST: 'api-planet-test'
            DB_MONGODB_NAME: 'api-planet'
            DB_MONGODB_ENDPOINT: 'mongodb://sw-mongo-db/'
            URL_SWAPI: 'https://swapi.dev/api/planets'
        ports:
            - 8000:8000
            - 5678:5678
        depends_on:
            - sw-mongo-db
        links:
            - sw-mongo-db

    sw-mongo-db:
        image: 'mongo'
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
